Repository beyond-sw-camp/be08-fin-EasyCheck-EasyStay-server, pull requests merged in 2024-10, with the labels that each got.

#108 [feat/#105] feat/#105/authPhone
  build.gradle
  src/main/java/com/beyond/easycheck/sms/exception/SmsMessageType.java
  src/main/java/com/beyond/easycheck/sms/infrastructure/persistence/redis/entity/SmsVerificationCode.java
  src/main/java/com/beyond/easycheck/sms/infrastructure/persistence/redis/entity/VerifiedPhone.java
  src/main/java/com/beyond/easycheck/sms/infrastructure/persistence/redis/repository/SmsVerificationCodeRepository.java
  src/main/java/com/beyond/easycheck/sms/infrastructure/persistence/redis/repository/SmsVerifiedPhoneRepository.java
  src/main/java/com/beyond/easycheck/sms/ui/controller/SmsController.java
  src/main/java/com/beyond/easycheck/sms/ui/requestbody/SmsCodeVerifyRequest.java
  src/main/java/com/beyond/easycheck/sms/ui/requestbody/SmsVerificationCodeRequest.java
Labels: Feat

#113 [feat/#111] feat/#111/authPermission
  src/main/java/com/beyond/easycheck/common/security/config/EasyCheckSecurityConfig.java
  src/main/java/com/beyond/easycheck/mail/infrastructure/persistence/redis/entity/VerifiedEmailEntity.java
  src/main/java/com/beyond/easycheck/permissions/application/service/PermissionOperationUseCase.java
  src/main/java/com/beyond/easycheck/permissions/application/service/PermissionReadUseCase.java
  src/main/java/com/beyond/easycheck/permissions/application/service/PermissionService.java
  src/main/java/com/beyond/easycheck/permissions/exception/PermissionMessageType.java
  src/main/java/com/beyond/easycheck/permissions/infrastructure/persistence/mariadb/entity/PermissionEntity.java
  src/main/java/com/beyond/easycheck/permissions/infrastructure/persistence/mariadb/entity/UserPermissionEntity.java
  src/main/java/com/beyond/easycheck/permissions/infrastructure/persistence/mariadb/repository/PermissionJpaRepository.java
  src/main/java/com/beyond/easycheck/permissions/infrastructure/persistence/mariadb/repository/UserPermissionJpaRepository.java
  src/main/java/com/beyond/easycheck/permissions/ui/controller/PermissionController.java
  src/main/java/com/beyond/easycheck/permissions/ui/requestbody/PermissionCreateRequest.java
  src/main/java/com/beyond/easycheck/permissions/ui/requestbody/PermissionGrantRequest.java
  src/main/java/com/beyond/easycheck/permissions/ui/requestbody/PermissionRevokeRequest.java
  src/main/java/com/beyond/easycheck/sms/infrastructure/persistence/redis/entity/VerifiedPhone.java
  src/main/java/com/beyond/easycheck/user/application/domain/EasyCheckUserDetails.java
  src/main/java/com/beyond/easycheck/user/application/domain/UserRole.java
  src/main/java/com/beyond/easycheck/user/application/service/UserService.java
  src/main/java/com/beyond/easycheck/user/exception/UserMessageType.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/permission/PermissionEntity.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/user/UserEntity.java
  src/test/java/com/beyond/easycheck/permissions/application/service/PermissionServiceTest.java
  src/test/java/com/beyond/easycheck/permissions/ui/controller/PermissionControllerTest.java
  src/test/java/com/beyond/easycheck/user/application/mock/WithEasyCheckMockUser.java
  src/test/java/com/beyond/easycheck/user/application/mock/WithEasyCheckMockUserSecurityContextFactory.java
  src/test/java/com/beyond/easycheck/user/application/service/UserServiceTest.java
Labels: Backend, Feat

#124 refactor: 불필요한 import 제거
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/ui/controller/AccommodationController.java
  src/main/java/com/beyond/easycheck/accomodations/ui/requestbody/AccommodationCreateRequest.java
Labels: Backend, Refactor

#125 [refactor//#121] refactor/#121/ReservationGetUserID
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationStatus.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/requestbody/ReservationRoomUpdateRequest.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/view/ReservationRoomView.java
Labels: Backend, Refactor

#118 [feat//#117] feat/#117/PaymentVerification
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/payments/application/validator/PaymentValidator.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/entity/PaymentEntity.java
  src/main/java/com/beyond/easycheck/payments/ui/controller/PaymentController.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/PaymentStatus.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationRoomEntity.java
Labels: Backend, Feat

#132 [refactor/#70/UpdateNotices] userId와 매핑
  src/main/java/com/beyond/easycheck/notices/application/service/NoticesService.java
  src/main/java/com/beyond/easycheck/notices/infrastructure/persistence/entity/NoticesEntity.java
  src/main/java/com/beyond/easycheck/notices/ui/controller/NoticesController.java
  src/main/java/com/beyond/easycheck/notices/ui/view/NoticesView.java
Labels: Backend, Refactor

#130 [refactor/#98/ReadSuggestions] userId와 매핑
  src/main/java/com/beyond/easycheck/suggestion/application/service/SuggestionService.java
  src/main/java/com/beyond/easycheck/suggestion/infrastructure/persistence/entity/SuggestionEntity.java
  src/main/java/com/beyond/easycheck/suggestion/ui/controller/SuggestionController.java
  src/main/java/com/beyond/easycheck/suggestion/ui/requestbody/SuggestionCreateRequest.java
  src/main/java/com/beyond/easycheck/suggestion/ui/view/SuggestionView.java
Labels: Backend, Refactor

#133 [refactor/#131/email] 이메일 내용 템플릿 generator
  src/main/java/com/beyond/easycheck/mail/application/service/MailServiceImpl.java
Labels: Backend, Refactor

#134 [feat/#119] feat/#119/EventCRUD
  src/main/java/com/beyond/easycheck/events/application/service/EventService.java
  src/main/java/com/beyond/easycheck/events/exception/EventMessageType.java
  src/main/java/com/beyond/easycheck/events/infrastructure/entity/EventEntity.java
  src/main/java/com/beyond/easycheck/events/infrastructure/repository/EventRepository.java
  src/main/java/com/beyond/easycheck/events/ui/controller/EventController.java
  src/main/java/com/beyond/easycheck/events/ui/requestbody/EventCreateRequest.java
  src/main/java/com/beyond/easycheck/events/ui/requestbody/EventUpdateRequest.java
  src/main/java/com/beyond/easycheck/events/ui/view/EventView.java
Labels: Backend, Feat

#137 [feat/#129] feat/#129/SendReservationDetailsEmail
  src/main/java/com/beyond/easycheck/mail/application/service/MailService.java
  src/main/java/com/beyond/easycheck/mail/application/service/MailServiceImpl.java
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/application/util/ReservationFormatUtil.java
Labels: Backend, Feat

#135 [feat/#4] feat/#4/CreateRooms
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomEntity.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomCreateRequest.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomUpdateRequest.java
  src/main/java/com/beyond/easycheck/rooms/ui/view/RoomView.java
Labels: Backend, Feat

#140 [refactor/#138] refactor/#138/VerificationReservation
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/exception/ReservationRoomMessageType.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/repository/ReservationRoomRepository.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/requestbody/ReservationRoomCreateRequest.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/view/ReservationRoomView.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomEntity.java
Labels: Backend, Refactor

#144 [feat/#143] feat/#143/VerificationAdditionalService
  src/main/java/com/beyond/easycheck/additionalservices/ui/controller/AdditionalServiceController.java
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/exception/ReservationRoomMessageType.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationservices/application/service/ReservationServiceService.java
  src/main/java/com/beyond/easycheck/reservationservices/exception/ReservationServiceMessageType.java
  src/main/java/com/beyond/easycheck/reservationservices/infrastructure/entity/ReservationServiceStatus.java
  src/main/java/com/beyond/easycheck/reservationservices/infrastructure/repository/ReservationServiceRepository.java
Labels: Backend, Feat

#146 [feat/#139/SuggestionReplyEmail] 건의사항에 대한 답변 메일 기능 구현
  src/main/java/com/beyond/easycheck/mail/application/service/MailService.java
  src/main/java/com/beyond/easycheck/mail/application/service/MailServiceImpl.java
  src/main/java/com/beyond/easycheck/suggestion/application/service/SuggestionService.java
  src/main/java/com/beyond/easycheck/suggestion/ui/controller/SuggestionController.java
  src/main/java/com/beyond/easycheck/suggestion/ui/requestbody/SuggestionReplyRequestBody.java
Labels: Backend, Feat

#147 [feat/#145] feat/#145/GetRoomAvailabilityByMonth
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/exception/ReservationRoomMessageType.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/view/DayRoomAvailabilityView.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/view/RoomAvailabilityView.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/DailyRoomAvailabilityEntity.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/DailyRoomAvailabilityRepository.java
  src/main/java/com/beyond/easycheck/rooms/ui/view/DayRoomAvailabilityView.java
Labels: Backend, Feat

#154 [feat/#150] feat/#150/AddingJPQL
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/view/DayRoomAvailabilityView.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/view/RoomAvailabilityView.java
  src/main/java/com/beyond/easycheck/rooms/application/service/DataInitializer.java
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/DailyRoomAvailabilityEntity.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/DailyRoomAvailabilityRepository.java
  src/main/java/com/beyond/easycheck/rooms/ui/view/DayRoomAvailabilityView.java
Labels: Backend, Feat

#153 [feat/#104] Feat/#104/ticket order
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketOrderOperationUseCase.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketOrderReadUseCase.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketOrderService.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/exception/TicketMessageType.java
  src/main/java/com/beyond/easycheck/tickets/exception/TicketOrderMessageType.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/CollectionAgreementType.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/OrderStatus.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/ReceiptMethodType.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketOrderEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketPaymentEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/repository/TicketOrderRepository.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/repository/TicketPaymentRepository.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketOrderController.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketPaymentController.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketOrderRequest.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketPaymentRequest.java
  src/main/java/com/beyond/easycheck/tickets/ui/view/TicketOrderDTO.java
Labels: Backend, Feat, Refactor

#157 feat: User Entity와 연관관계 설정
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketOrderService.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketReadUseCase.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketOrderEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketPaymentEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/repository/TicketOrderRepository.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketController.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketRequest.java
  src/main/java/com/beyond/easycheck/tickets/ui/view/TicketOrderDTO.java
Labels: Backend, Feat

#158 [test/#149/NoticesTest] Notices 테스트 코드 작성
  src/test/java/com/beyond/easycheck/notices/application/service/NoticesServiceTest.java
  src/test/java/com/beyond/easycheck/notices/ui/controller/NoticesControllerTest.java
  src/test/resources/sql/accommodation.sql
Labels: Backend, Test

#159 Test#149/notices test
  src/main/java/com/beyond/easycheck/notices/application/service/NoticesService.java
  src/test/java/com/beyond/easycheck/notices/application/service/NoticesServiceTest.java
  src/test/java/com/beyond/easycheck/notices/ui/controller/NoticesControllerTest.java
  src/test/java/com/beyond/easycheck/suggestion/application/service/SuggestionServiceTest.java
Labels: Backend, Test

#160 [feat/#148] feat/#148/GetRoomAvailabilityByCheckInCheckOut
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/repository/ReservationRoomRepository.java
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/DailyRoomAvailabilityEntity.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomEntity.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
Labels: Backend, Feat

#163 [refactor/#162] refactor/#162/RefactorCreateReservation
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
Labels: Backend, Refactor

#168 [refactor/#162] refactor/#162/RefactorCreateReservation
  src/main/java/com/beyond/easycheck/mail/application/service/MailServiceImpl.java
  src/main/java/com/beyond/easycheck/payments/ui/view/PaymentView.java
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/requestbody/ReservationRoomCreateRequest.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/view/ReservationRoomView.java
  src/main/java/com/beyond/easycheck/rooms/application/service/DataInitializer.java
Labels: Backend, Refactor

#170 test : SuggestionServiceTest, SuggestionControllerTest 테스트 코드 작성
  src/main/java/com/beyond/easycheck/suggestion/application/service/SuggestionService.java
  src/test/java/com/beyond/easycheck/notices/application/service/NoticesServiceTest.java
  src/test/java/com/beyond/easycheck/suggestion/application/service/SuggestionServiceTest.java
  src/test/java/com/beyond/easycheck/suggestion/ui/controller/SuggestionControllerTest.java
Labels: Backend, Test

#171 [refactor/#169] refactor/#169/ReadRoomByCheckInCheckOut
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/repository/ReservationRoomRepository.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/requestbody/ReservationRoomCreateRequest.java
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/DailyRoomAvailabilityEntity.java
Labels: Backend, Refactor

#173 [test/#172] test/#172/AccommodationServiceTest
  src/test/java/com/beyond/easycheck/accommodations/application/service/AccommodationServiceTest.java
  src/test/java/com/beyond/easycheck/accommodations/ui/controller/AccommodationControllerTest.java
Labels: Backend, Test

#175 [test/#136] test/#136/RoomTest
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/exception/RoomMessageType.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomEntity.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomCreateRequest.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomUpdateRequest.java
  src/main/java/com/beyond/easycheck/rooms/ui/view/RoomView.java
  src/main/java/com/beyond/easycheck/roomtypes/infrastructure/entity/RoomtypeEntity.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomtypeCreateRequest.java
  src/test/java/com/beyond/easycheck/rooms/application/service/RoomServiceTest.java
  src/test/java/com/beyond/easycheck/rooms/ui/controller/RoomControllerTest.java
  src/test/resources/sql/accommodation.sql
  src/test/resources/sql/roomtype.sql
Labels: Backend, Test

#177 [test/#176] test/#176/SeasonTest
  src/main/java/com/beyond/easycheck/seasons/application/service/SeasonService.java
  src/main/java/com/beyond/easycheck/seasons/exception/SeasonMessageType.java
  src/main/java/com/beyond/easycheck/seasons/ui/controller/SeasonController.java
  src/main/java/com/beyond/easycheck/seasons/ui/requestbody/SeasonCreateRequest.java
  src/main/java/com/beyond/easycheck/seasons/ui/requestbody/SeasonUpdateRequest.java
  src/test/java/com/beyond/easycheck/rooms/application/service/RoomServiceTest.java
  src/test/java/com/beyond/easycheck/seasons/application/service/SeasonServiceTest.java
  src/test/java/com/beyond/easycheck/seasons/ui/controller/SeasonControllerTest.java
Labels: Backend

#179 [Test/#155] Test/#155/themepark test
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkCreateRequest.java
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkUpdateRequest.java
  src/test/java/com/beyond/easycheck/themeparks/application/service/ThemeParkServiceTest.java
  src/test/java/com/beyond/easycheck/themeparks/ui/controller/ThemeParkControllerTest.java
Labels: Backend, Refactor, Test

#183 [test/#176] test/#176/SeasonControllerTest
  src/main/java/com/beyond/easycheck/seasons/application/service/SeasonService.java
  src/main/java/com/beyond/easycheck/seasons/ui/controller/SeasonController.java
  src/test/java/com/beyond/easycheck/seasons/ui/controller/SeasonControllerTest.java
Labels: Backend, Test

#184 [test/#174] test/#174/ReservationRoomTest
  src/main/java/com/beyond/easycheck/mail/application/service/MailService.java
  src/main/java/com/beyond/easycheck/mail/application/service/MailServiceImpl.java
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/payments/application/validator/PaymentValidator.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/entity/PaymentEntity.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/PaymentStatus.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationStatus.java
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationrooms/application/util/ReservationFormatUtil.java
  src/main/java/com/beyond/easycheck/reservationrooms/exception/ReservationRoomMessageType.java
  src/main/java/com/beyond/easycheck/reservationrooms/infrastructure/entity/PaymentStatus.java
  src/main/java/com/beyond/easycheck/reservationrooms/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationrooms/infrastructure/entity/ReservationStatus.java
  src/main/java/com/beyond/easycheck/reservationrooms/infrastructure/repository/ReservationRoomRepository.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/requestbody/ReservationRoomCreateRequest.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/requestbody/ReservationRoomUpdateRequest.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/view/DayRoomAvailabilityView.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/view/ReservationRoomView.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/view/RoomAvailabilityView.java
  src/main/java/com/beyond/easycheck/reservationservices/application/service/ReservationServiceService.java
  src/main/java/com/beyond/easycheck/reservationservices/infrastructure/entity/ReservationServiceEntity.java
  src/main/java/com/beyond/easycheck/reservationservices/infrastructure/repository/ReservationServiceRepository.java
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/test/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomServiceTest.java
  src/test/java/com/beyond/easycheck/reservationrooms/ui/controller/ReservationRoomControllerTest.java
Labels: Backend, Test

#186 Feat/#181/imageupload
  src/main/java/com/beyond/easycheck/common/doc/WebConfig.java
  src/main/java/com/beyond/easycheck/common/entity/OctetStreamReadMsgConverter.java
  src/main/java/com/beyond/easycheck/s3/application/service/S3Service.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkOperationUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkReadUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkService.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/entity/ThemeParkEntity.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/repository/ThemeParkRepository.java
  src/main/java/com/beyond/easycheck/themeParks/ui/controller/ThemeParkController.java
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkCreateRequest.java
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkUpdateRequest.java
  src/main/java/com/beyond/easycheck/themeParks/ui/view/ThemeParkView.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/ReceiptMethodType.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketOrderRequest.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketPaymentRequest.java
  src/test/java/com/beyond/easycheck/attractions/application/service/AttractionServiceTest.java
  src/test/java/com/beyond/easycheck/themeparks/application/service/ThemeParkServiceTest.java
  src/test/java/com/beyond/easycheck/themeparks/ui/controller/ThemeParkControllerTest.java
Labels: Backend, Feat, Refactor, Test

#191 [feat/#185] feat/#185/RoomImageUpload
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/exception/RoomMessageType.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomEntity.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/ImageRepository.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomCreateRequest.java
  src/main/java/com/beyond/easycheck/rooms/ui/view/RoomView.java
  src/main/java/com/beyond/easycheck/s3/application/domain/FileManagementCategory.java
  src/main/java/com/beyond/easycheck/s3/application/service/S3Service.java
  src/test/java/com/beyond/easycheck/rooms/application/service/RoomServiceTest.java
  src/test/java/com/beyond/easycheck/rooms/ui/controller/RoomControllerTest.java
Labels: Backend, Feat

#193 Test/#187/room type test
  src/main/java/com/beyond/easycheck/roomtypes/application/service/RoomtypeService.java
  src/main/java/com/beyond/easycheck/roomtypes/exception/RoomtypeMessageType.java
  src/test/java/com/beyond/easycheck/roomtypes/application/service/RoomtypeServiceTest.java
  src/test/java/com/beyond/easycheck/roomtypes/ui/controller/RoomtypeControllerTest.java
  src/test/java/com/beyond/easycheck/suggestion/application/service/SuggestionServiceTest.java
  src/test/resources/sql/accommodation.sql
  src/test/resources/sql/roomtype.sql
Labels: Backend, Test

#192 [Test/#188/additionalservice] 부가기능 CRUD 테스트
  src/main/java/com/beyond/easycheck/additionalservices/application/service/AdditionalServiceService.java
  src/test/java/com/beyond/easycheck/additionalservices/application/service/AdditionalServiceServiceTest.java
Labels: Backend, Test

#194 [test/#190] test/#190/PaymentTest
  src/test/java/com/beyond/easycheck/payments/application/service/PaymentServiceTest.java
  src/test/java/com/beyond/easycheck/payments/ui/controller/PaymentControllerTest.java
Labels: Backend, Test

#196 [test/#136] test/#136/RoomTest
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/RoomImageRepository.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomUpdateRequest.java
  src/test/java/com/beyond/easycheck/rooms/application/service/RoomServiceTest.java
  src/test/java/com/beyond/easycheck/rooms/ui/controller/RoomControllerTest.java
Labels: Backend, Test

#197 refactor: 불필요한 어노테이션 제거
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
Labels: Backend, Refactor

#198 [test/#178] test/#178/RoomrateTest
  src/main/java/com/beyond/easycheck/roomrates/application/service/RoomrateService.java
  src/main/java/com/beyond/easycheck/roomrates/exception/RoomrateMessageType.java
  src/main/java/com/beyond/easycheck/roomrates/ui/controller/RoomrateController.java
  src/main/java/com/beyond/easycheck/roomrates/ui/requestbody/RoomrateUpdateRequest.java
  src/main/java/com/beyond/easycheck/seasons/ui/controller/SeasonController.java
  src/test/java/com/beyond/easycheck/roomrates/application/service/RoomrateServiceTest.java
  src/test/java/com/beyond/easycheck/roomrates/ui/controller/RoomratesControllerTest.java
Labels: Backend, Test

#201 [feat/#200] feat/#200/EventImage
  src/main/java/com/beyond/easycheck/events/application/service/EventService.java
  src/main/java/com/beyond/easycheck/events/infrastructure/entity/EventEntity.java
  src/main/java/com/beyond/easycheck/events/infrastructure/repository/EventImageRepository.java
  src/main/java/com/beyond/easycheck/events/ui/controller/EventController.java
  src/main/java/com/beyond/easycheck/events/ui/requestbody/EventCreateRequest.java
  src/main/java/com/beyond/easycheck/events/ui/requestbody/EventUpdateRequest.java
  src/main/java/com/beyond/easycheck/events/ui/view/EventView.java
  src/test/java/com/beyond/easycheck/events/application/service/EventServiceTest.java
Labels: Backend, Feat

#202 test : RoomtypeControllerTest 테스트 코드 작성
  src/test/java/com/beyond/easycheck/roomtypes/application/service/RoomtypeServiceTest.java
  src/test/java/com/beyond/easycheck/roomtypes/ui/controller/RoomtypeControllerTest.java
  src/test/resources/sql/roomtype.sql
Labels: Backend, Test

#203 [feat/#195] feat/#195/FacilitiesLinkS3
  src/main/java/com/beyond/easycheck/facilities/application/service/FacilityService.java
  src/main/java/com/beyond/easycheck/facilities/infrastructure/entity/FacilityEntity.java
  src/main/java/com/beyond/easycheck/facilities/ui/controller/FacilityController.java
  src/main/java/com/beyond/easycheck/facilities/ui/view/FacilityView.java
Labels: Backend, Feat

#206 [refactor/#205] refactor/#205/ChangeMethodName
  src/main/java/com/beyond/easycheck/facilities/application/service/FacilityService.java
Labels: Backend, Refactor

#207 [test/#199] test/#199/EventTest
  src/main/java/com/beyond/easycheck/events/application/service/EventService.java
  src/main/java/com/beyond/easycheck/events/exception/EventMessageType.java
  src/main/java/com/beyond/easycheck/events/ui/controller/EventController.java
  src/main/java/com/beyond/easycheck/events/ui/requestbody/EventCreateRequest.java
  src/main/java/com/beyond/easycheck/events/ui/requestbody/EventUpdateRequest.java
  src/test/java/com/beyond/easycheck/events/application/service/EventServiceTest.java
  src/test/java/com/beyond/easycheck/events/ui/controller/EventControllerTest.java
  src/test/java/com/beyond/easycheck/rooms/ui/controller/RoomControllerTest.java
Labels: Backend, Test

#208 [refactor/#195] refactor/#195/FacilitiesLinkS3
  src/main/java/com/beyond/easycheck/facilities/application/service/FacilityService.java
  src/main/java/com/beyond/easycheck/facilities/exception/FacilityMessageType.java
  src/main/java/com/beyond/easycheck/facilities/ui/controller/FacilityController.java
Labels: Backend, Refactor

#209 [test/#204] test/#204/FacilityTest
  src/test/java/com/beyond/easycheck/facilities/application/service/FacilityServiceTest.java
  src/test/java/com/beyond/easycheck/facilities/ui/controller/FacilityControllerTest.java
Labels: Backend, Test

#211 [refactor/#210] refactor/#210/ReservationGetImage
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/view/ReservationRoomView.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/view/RoomAvailabilityView.java
  src/test/java/com/beyond/easycheck/reservationrooms/ui/controller/ReservationRoomControllerTest.java
Labels: Backend, Refactor

#213 test: ReservationRoom 테스트 수정
  src/test/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomServiceTest.java
  src/test/java/com/beyond/easycheck/reservationrooms/ui/controller/ReservationRoomControllerTest.java
Labels: Backend, Test

#217 [test/#199] test/#199/EventTest
  src/main/java/com/beyond/easycheck/events/application/service/EventService.java
  src/main/java/com/beyond/easycheck/events/ui/controller/EventController.java
  src/test/java/com/beyond/easycheck/events/application/service/EventServiceTest.java
  src/test/java/com/beyond/easycheck/events/ui/controller/EventControllerTest.java
  src/test/java/com/beyond/easycheck/themeparks/ui/controller/ThemeParkControllerTest.java
Labels: Backend, Test

#218 [test/#178] test/#178/RoomrateTest
  src/main/java/com/beyond/easycheck/roomrates/ui/controller/RoomrateController.java
  src/test/java/com/beyond/easycheck/roomrates/application/service/RoomrateServiceTest.java
  src/test/java/com/beyond/easycheck/roomrates/ui/controller/RoomrateControllerTest.java
Labels: Backend, Test

#216 [refactor/#215] refactor/#215/AddFailTest
  src/test/java/com/beyond/easycheck/accommodations/application/service/AccommodationServiceTest.java
  src/test/java/com/beyond/easycheck/accommodations/ui/controller/AccommodationControllerTest.java
Labels: Backend, Refactor

#220 [Test/#189/additionalservice] 부가서비스 예약 테스트
  src/main/java/com/beyond/easycheck/reservationservices/ui/requestbody/ReservationServiceUpdateRequest.java
  src/test/java/com/beyond/easycheck/reservationservices/application/service/ReservationServiceServiceTest.java
  src/test/java/com/beyond/easycheck/reservationservices/ui/controller/ReservationServiceControllerTest.java
Labels: Backend, Test

#222 [Test/#221/additionalservice] 부가서비스 컨트롤러 테스트
  src/main/java/com/beyond/easycheck/additionalservices/ui/controller/AdditionalServiceController.java
  src/test/java/com/beyond/easycheck/additionalservices/ui/controller/AdditionalServiceControllerTest.java
Labels: Backend, Test

#223 [refactor/#219] refactor/#219/AddFailPaymentTest
  src/main/java/com/beyond/easycheck/payments/exception/PaymentMessageType.java
  src/main/java/com/beyond/easycheck/reservationrooms/exception/ReservationRoomMessageType.java
  src/test/java/com/beyond/easycheck/payments/application/service/PaymentServiceTest.java
Labels: Backend, Refactor

#225 refactor: 테스트 Mockito로 변경
  src/test/java/com/beyond/easycheck/permissions/application/service/PermissionServiceTest.java
  src/test/java/com/beyond/easycheck/permissions/ui/controller/PermissionControllerTest.java
Labels: Backend, Refactor, Test

#229 [refactor/#228] refactor/#228/RoomTest
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/exception/RoomMessageType.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomUpdateRequest.java
  src/test/java/com/beyond/easycheck/rooms/application/service/RoomServiceTest.java
  src/test/java/com/beyond/easycheck/rooms/ui/controller/RoomControllerTest.java
Labels: Backend, Refactor

#232 [feat/#231] feat/#231/attraction s3service
  src/main/java/com/beyond/easycheck/attractions/application/service/AttractionOperationUseCase.java
  src/main/java/com/beyond/easycheck/attractions/application/service/AttractionReadUseCase.java
  src/main/java/com/beyond/easycheck/attractions/application/service/AttractionService.java
  src/main/java/com/beyond/easycheck/attractions/infrastructure/entity/AttractionEntity.java
  src/main/java/com/beyond/easycheck/attractions/ui/controller/AttractionController.java
  src/main/java/com/beyond/easycheck/attractions/ui/view/AttractionView.java
  src/main/java/com/beyond/easycheck/s3/application/domain/FileManagementCategory.java
Labels: Backend, Feat

#233 [Test/#230] Test/#230/test themepark,attraction
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkService.java
  src/test/java/com/beyond/easycheck/attractions/application/service/AttractionServiceTest.java
  src/test/java/com/beyond/easycheck/attractions/ui/controller/AttractionControllerTest.java
  src/test/java/com/beyond/easycheck/themeparks/application/service/ThemeParkServiceTest.java
  src/test/java/com/beyond/easycheck/themeparks/ui/controller/ThemeParkControllerTest.java
Labels: Backend, Refactor, Test

#237 Feat/#104/ticket order
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketOrderService.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/exception/TicketOrderMessageType.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/OrderStatus.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/PaymentStatus.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketOrderEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketPaymentEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/repository/TicketPaymentRepository.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketPaymentController.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketPaymentRequest.java
  src/test/java/com/beyond/easycheck/tickets/application/service/TicketOrderServiceTest.java
Labels: Backend, Feat, Refactor

#238 [Test/#236] Test/#236/TicketPaymentTest
  src/test/java/com/beyond/easycheck/tickets/application/service/TicketPaymentServiceTest.java
  src/test/java/com/beyond/easycheck/tickets/ui/controller/TicketPaymentControllerTest.java
Labels: Backend, Test

#240 [refactor/#239] refactor/#239/AccommodationLinkS3
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/ui/view/AccommodationView.java
Labels: Backend, Refactor

#244 [refactor/#243] refactor/#243/AddColumnAccommodation
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/entity/AccommodationEntity.java
  src/main/java/com/beyond/easycheck/accomodations/ui/controller/AccommodationController.java
  src/main/java/com/beyond/easycheck/accomodations/ui/requestbody/AccommodationCreateRequest.java
  src/main/java/com/beyond/easycheck/accomodations/ui/view/AccommodationView.java
  src/main/java/com/beyond/easycheck/s3/application/domain/FileManagementCategory.java
Labels: Backend, Refactor

#247 [chore/#246/security] 모든 GET 요청 허용
  src/main/java/com/beyond/easycheck/common/security/config/EasyCheckSecurityConfig.java
Labels: Backend, Chore

#248 [refactor/#245] refactor/#245/AddResponseTimeColumn
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/entity/AccommodationEntity.java
  src/main/java/com/beyond/easycheck/accomodations/ui/requestbody/AccommodationCreateRequest.java
  src/main/java/com/beyond/easycheck/accomodations/ui/requestbody/AccommodationUpdateRequest.java
  src/main/java/com/beyond/easycheck/accomodations/ui/view/AccommodationView.java
Labels: Backend, Refactor

#250 [feat/#249] feat/#249/PaymentSystemThroughPortOne
  build.gradle
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/payments/exception/PaymentMessageType.java
  src/main/java/com/beyond/easycheck/payments/ui/requestbody/PaymentCreateRequest.java
Labels: Backend, Feat

#252 refactor: 예약 가능한 객실 조회 시 AccommodationId 불러오기
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/controller/ReservationRoomController.java
Labels: Backend, Refactor

#253 [refactor/#251] refactor/#251/ReservationGetAccommodationId
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
Labels: Backend, Refactor

#255 [chore/#254/cors] cors 개발용 설정
  src/main/java/com/beyond/easycheck/common/security/config/EasyCheckSecurityConfig.java
Labels: Backend, Chore

#257 refactor: GetAllAccommodations 메소드 변경
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/ui/controller/AccommodationController.java
Labels: Backend, Refactor

#263 [Feat/#262/user-info] 유저 정보 불러오는 API 추가
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/entity/AccommodationEntity.java
  src/main/java/com/beyond/easycheck/common/security/config/EasyCheckSecurityConfig.java
  src/main/java/com/beyond/easycheck/user/application/service/user/UserReadUseCase.java
  src/main/java/com/beyond/easycheck/user/ui/controller/UserController.java
Labels: Backend, Feat

#260 [refactor/#259] refactor/#259/AddResponseBody
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/payments/ui/view/PaymentView.java
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/controller/ReservationRoomController.java
Labels: Backend, Refactor

#265 [refactor/#265/signup] 회원가입 할 때 이메일 인증 안해도 되도록 변경
  src/main/java/com/beyond/easycheck/user/application/service/user/UserService.java
Labels: Backend, Refactor

#268 feat: ticketAvailable ThemeParkView에 추가.
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkReadUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/ui/view/ThemeParkView.java
Labels: Backend, Feat

#270 [feat/#269] feat/#269/RefundPayment
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/payments/exception/PaymentMessageType.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/entity/CompletionStatus.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/entity/PaymentEntity.java
  src/main/java/com/beyond/easycheck/payments/ui/controller/PaymentController.java
  src/main/java/com/beyond/easycheck/payments/ui/requestbody/PaymentUpdateRequest.java
  src/main/java/com/beyond/easycheck/payments/ui/view/PaymentView.java
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationrooms/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/view/RoomAvailabilityView.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/DailyRoomAvailabilityEntity.java
Labels: Backend, Feat

#274 [chore/#273/controller-swagger]: 컨트롤러에 스웨거 어노테이션 추가
  src/main/java/com/beyond/easycheck/admin/ui/controller/AdminController.java
  src/main/java/com/beyond/easycheck/common/ui/controller/CommonController.java
  src/main/java/com/beyond/easycheck/mail/ui/controller/EmailController.java
  src/main/java/com/beyond/easycheck/sms/ui/controller/SmsController.java
  src/main/java/com/beyond/easycheck/user/ui/controller/CorporateUserController.java
  src/main/java/com/beyond/easycheck/user/ui/controller/GuestController.java
Labels: Backend, Chore

#276 [feat/#275/admin] 어트랙션, 결제 관련 전체 조회
  src/main/java/com/beyond/easycheck/admin/application/service/AdminReadUseCase.java
  src/main/java/com/beyond/easycheck/admin/application/service/AdminService.java
  src/main/java/com/beyond/easycheck/admin/ui/controller/AdminController.java
  src/main/java/com/beyond/easycheck/admin/ui/view/AttractionView.java
  src/main/java/com/beyond/easycheck/admin/ui/view/PaymentView.java
  src/main/java/com/beyond/easycheck/attractions/infrastructure/repository/AttractionRepository.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/repository/PaymentRepository.java
Labels: Backend, Feat

#279 [fix/#278] fix/#278/FixN+1
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/DailyRoomAvailabilityRepository.java
Labels: Backend, Fix

#282 [Feat/#281/accommodation-rooms] 객실 조건부 검색 기능 추가
  .gitignore
  build.gradle
  src/main/java/com/beyond/easycheck/common/doc/QuerydslConfig.java
  src/main/java/com/beyond/easycheck/rooms/application/dto/RoomFindQuery.java
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/RoomRepository.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/RoomRepositoryCustom.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/RoomRepositoryImpl.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
Labels: Backend, Feat

#285 Feat/#284/TicketPaymentSystemThroughPortOne
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketPaymentEntity.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketPaymentController.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketPaymentRequest.java
  src/test/java/com/beyond/easycheck/tickets/ui/controller/TicketPaymentControllerTest.java
Labels: Backend, Feat, Refactor

#286 [Feat/#283/events] 이벤트 전체 조회 동적 쿼리 추가
  src/main/java/com/beyond/easycheck/events/application/service/EventService.java
  src/main/java/com/beyond/easycheck/events/application/service/dto/EventFindQuery.java
  src/main/java/com/beyond/easycheck/events/infrastructure/repository/EventRepository.java
  src/main/java/com/beyond/easycheck/events/infrastructure/repository/EventRepositoryCustom.java
  src/main/java/com/beyond/easycheck/events/infrastructure/repository/EventRepositoryImpl.java
  src/main/java/com/beyond/easycheck/events/ui/controller/EventController.java
Labels: Backend, Feat

#290 [feat#289] feat/#289/TicketOrderDetails
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketOrderService.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/OrderDetailsEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketOrderEntity.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketOrderRequest.java
  src/main/java/com/beyond/easycheck/tickets/ui/view/OrderDetailsDTO.java
  src/main/java/com/beyond/easycheck/tickets/ui/view/TicketOrderDTO.java
Labels: Backend, Feat

#292 [feat/#291/users] 유저 정보 수정 및 탈퇴처리
  src/main/java/com/beyond/easycheck/user/application/service/UserOperationUseCase.java
  src/main/java/com/beyond/easycheck/user/application/service/UserService.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/user/UserEntity.java
  src/main/java/com/beyond/easycheck/user/ui/controller/UserController.java
  src/main/java/com/beyond/easycheck/user/ui/requestbody/UserUpdateRequest.java
  src/test/java/com/beyond/easycheck/user/application/service/user/UserServiceTest.java
Labels: Backend, Feat

#296 [feat/#280] feat/#280/AddDepositWithoutABankbook
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/entity/PaymentEntity.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/repository/PaymentRepository.java
  src/main/java/com/beyond/easycheck/payments/ui/controller/PaymentController.java
  src/main/java/com/beyond/easycheck/payments/ui/requestbody/PaymentCreateRequest.java
  src/main/java/com/beyond/easycheck/payments/ui/requestbody/WebhookRequest.java
Labels: Backend, Feat

#301 [feat/#297] 배치와 스케쥴러를 사용한 예약 안내 메일 재전송
  build.gradle
  src/main/java/com/beyond/easycheck/EasycheckApplication.java
  src/main/java/com/beyond/easycheck/common/doc/BatchConfig.java
  src/main/java/com/beyond/easycheck/common/doc/SchedulerConfig.java
  src/main/java/com/beyond/easycheck/mail/application/service/MailService.java
  src/main/java/com/beyond/easycheck/mail/application/service/MailServiceImpl.java
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationrooms/infrastructure/repository/ReservationRoomRepository.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/requestbody/ReservationRoomUpdateRequest.java
Labels: Backend, Feat

#303 [Refactor/#288/room] 객실 테이블 컬럼 추가, 변경
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/view/ReservationRoomView.java
  src/main/java/com/beyond/easycheck/roomrates/application/service/RoomrateService.java
  src/main/java/com/beyond/easycheck/rooms/application/dto/FindRoomResult.java
  src/main/java/com/beyond/easycheck/rooms/application/dto/RoomFindQuery.java
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomEntity.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/RoomRepository.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/RoomRepositoryImpl.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomCreateRequest.java
  src/main/java/com/beyond/easycheck/rooms/ui/view/RoomView.java
  src/main/java/com/beyond/easycheck/roomtypes/application/service/RoomtypeService.java
  src/main/java/com/beyond/easycheck/roomtypes/infrastructure/entity/RoomtypeEntity.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomtypeUpdateRequest.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/view/RoomtypeView.java
  src/test/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomServiceTest.java
  src/test/java/com/beyond/easycheck/rooms/application/service/RoomServiceTest.java
  src/test/java/com/beyond/easycheck/rooms/ui/controller/RoomControllerTest.java
  src/test/java/com/beyond/easycheck/roomtypes/application/service/RoomtypeServiceTest.java
  src/test/java/com/beyond/easycheck/roomtypes/ui/controller/RoomtypeControllerTest.java
Labels: Backend, Refactor

#308 Refactor/#307/room type
  src/main/java/com/beyond/easycheck/roomtypes/application/dto/FindRoomTypeResult.java
  src/main/java/com/beyond/easycheck/roomtypes/application/service/RoomtypeService.java
  src/main/java/com/beyond/easycheck/roomtypes/infrastructure/entity/RoomtypeEntity.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomtypeCreateRequest.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomtypeUpdateRequest.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/view/RoomtypeView.java
  src/test/java/com/beyond/easycheck/roomtypes/application/service/RoomtypeServiceTest.java
  src/test/java/com/beyond/easycheck/roomtypes/ui/controller/RoomtypeControllerTest.java
Labels: Backend, Refactor

#309 [Feat/#308/corp-user] 법인회원 회원가입
  src/main/java/com/beyond/easycheck/common/security/config/EasyCheckSecurityConfig.java
  src/main/java/com/beyond/easycheck/user/application/service/UserOperationUseCase.java
  src/main/java/com/beyond/easycheck/user/application/service/UserService.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/user/UserEntity.java
  src/main/java/com/beyond/easycheck/user/ui/controller/CorporateUserController.java
  src/main/java/com/beyond/easycheck/user/ui/requestbody/CorporateUserRegisterRequest.java
Labels: Backend, Feat, Refactor

#312 [refactor/#310] refactor/#310/AddInitializeRoomAvailability
  src/main/java/com/beyond/easycheck/common/doc/BatchConfig.java
  src/main/java/com/beyond/easycheck/common/doc/SchedulerConfig.java
  src/main/java/com/beyond/easycheck/rooms/application/service/DataInitializer.java
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
Labels: Backend, Refactor

#321 [refactor/#320] PaymentView에 PaymentDate 추가
  src/main/java/com/beyond/easycheck/payments/ui/view/PaymentView.java
Labels: Backend, Refactor

#323 [refactor/#320] PaymentView에 accommodationName 추가
  src/main/java/com/beyond/easycheck/payments/ui/view/PaymentView.java
Labels: Backend, Refactor

#325 refactor: 예약 생성시 필요 컬럼 추가
  src/main/java/com/beyond/easycheck/reservationrooms/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationrooms/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/requestbody/ReservationRoomCreateRequest.java
  src/main/java/com/beyond/easycheck/reservationrooms/ui/view/ReservationRoomView.java
Labels: Backend, Feat, Refactor

#329 [feat/#322] feat/#322/SendMailPayment
  src/main/java/com/beyond/easycheck/mail/application/service/MailService.java
  src/main/java/com/beyond/easycheck/mail/application/service/MailServiceImpl.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/application/util/TicketPaymentFormatUtil.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketPaymentController.java
  src/main/java/com/beyond/easycheck/tickets/ui/view/TicketPaymentView.java
  src/test/java/com/beyond/easycheck/payments/ui/controller/PaymentControllerTest.java
Labels: Backend, Feat

#331 [feat/#330] feat/#330/RefundTicketPayment
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/exception/TicketOrderMessageType.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketOrderEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketPaymentEntity.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketPaymentController.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketPaymentUpdateRequest.java
Labels: Backend, Feat

#332 [refactor/#330]
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/ui/view/TicketPaymentView.java
Labels: Backend, Refactor

#335 [feat/#300] feat/#300/point
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/payments/ui/view/PaymentView.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/ui/view/TicketPaymentView.java
  src/main/java/com/beyond/easycheck/user/application/service/UserOperationUseCase.java
  src/main/java/com/beyond/easycheck/user/application/service/UserReadUseCase.java
  src/main/java/com/beyond/easycheck/user/application/service/UserService.java
  src/main/java/com/beyond/easycheck/user/exception/UserMessageType.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/user/UserEntity.java
Labels: Backend, Feat

#339 [feat/#338] feat/#338/AddTicketVBank
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/application/util/TicketPaymentFormatUtil.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/ReceiptMethodType.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketPaymentEntity.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketPaymentRequest.java
  src/test/java/com/beyond/easycheck/payments/application/service/PaymentServiceTest.java
Labels: Backend, Feat

#340 [feat/#338] feat/#338/AddTicketVBank
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketPaymentService.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketPaymentEntity.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketPaymentController.java
Labels: Backend, Feat
