Repository beyond-sw-camp/be08-fin-EasyCheck-EasyStay-server, pull requests merged in 2024-09, with the labels that each got.

#8 Chore/#3/settings
  build.gradle
  src/main/java/com/beyond/easycheck/common/doc/SwaggerConfig.java
  src/main/java/com/beyond/easycheck/common/exception/CommonMessageType.java
  src/main/java/com/beyond/easycheck/common/exception/EasyCheckException.java
  src/main/java/com/beyond/easycheck/common/exception/MessageType.java
  src/main/java/com/beyond/easycheck/common/security/EasyCheckSecurityConfig.java
  src/main/java/com/beyond/easycheck/common/ui/advice/EasyCheckRestControllerAdvice.java
  src/main/java/com/beyond/easycheck/common/ui/controller/CommonController.java
  src/main/java/com/beyond/easycheck/common/ui/view/ApiErrorView.java
Labels: Chore

#12 [feat/#1] branch: feat/#1/CreateFacilities
  src/main/java/com/beyond/easycheck/EasycheckApplication.java
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/entity/Accommodation.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/entity/AccommodationType.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/repository/AccommodationRepository.java
  src/main/java/com/beyond/easycheck/accomodations/ui/controller/AccommodationController.java
  src/main/java/com/beyond/easycheck/accomodations/ui/requestbody/AccommodationCreateRequest.java
Labels: Backend, Feat

#14 [feat/#5] create theme parks
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkOperationUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkReadUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkService.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/persistence/entity/ThemeParkEntity.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/persistence/repository/ThemeParkRepository.java
  src/main/java/com/beyond/easycheck/themeParks/ui/controller/ThemeParkController.java
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkCreateRequest.java
  src/main/java/com/beyond/easycheck/themeParks/ui/view/ApiResponseView.java
  src/main/java/com/beyond/easycheck/themeParks/ui/view/ThemeParkView.java
Labels: Backend, Feat

#16 [feat/#13] feat/#13/ReadAccommodation
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/exception/AccommodationMessageType.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/entity/AccommodationEntity.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/repository/AccommodationRepository.java
  src/main/java/com/beyond/easycheck/accomodations/ui/controller/AccommodationController.java
  src/main/java/com/beyond/easycheck/accomodations/ui/view/AccommodationView.java
Labels: Backend, Feat

#22 [feat/#20] feat/#20/DeleteAccommodation
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/ui/controller/AccommodationController.java
Labels: Backend, Feat

#25 [feat/#24] feat/#24/CreateAdditionalServices
  src/main/java/com/beyond/easycheck/additionalservices/application/service/AdditionalServiceService.java
  src/main/java/com/beyond/easycheck/additionalservices/exception/AdditionalServiceMessageType.java
  src/main/java/com/beyond/easycheck/additionalservices/infrastructure/entity/AdditionalServiceEntity.java
  src/main/java/com/beyond/easycheck/additionalservices/infrastructure/repository/AdditionalServiceRepository.java
  src/main/java/com/beyond/easycheck/additionalservices/ui/controller/AdditionalServiceController.java
  src/main/java/com/beyond/easycheck/additionalservices/ui/requestbody/AdditionalServiceCreateRequest.java
Labels: Backend, Feat

#18 [feat/#15] feat/#15/ReadThemePark
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkOperationUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkReadUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkService.java
  src/main/java/com/beyond/easycheck/themeParks/exception/ThemeParkMessageType.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/persistence/repository/ThemeParkRepository.java
  src/main/java/com/beyond/easycheck/themeParks/ui/controller/ThemeParkController.java
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkCreateRequest.java
Labels: Backend, Feat

#33 [feat/#31] feat/#31/CreateRoomType
  src/main/java/com/beyond/easycheck/EasycheckApplication.java
  src/main/java/com/beyond/easycheck/roomType/application/service/RoomTypeService.java
  src/main/java/com/beyond/easycheck/roomType/infrastructure/entity/RoomTypeEntity.java
  src/main/java/com/beyond/easycheck/roomType/infrastructure/repository/RoomTypeRepository.java
  src/main/java/com/beyond/easycheck/roomType/ui/controller/RoomTypeController.java
  src/main/java/com/beyond/easycheck/roomType/ui/requestbody/RoomTypeCreateRequest.java
Labels: Backend, Feat

#35 [feat/#34] feat/#34/DeleteRoomType
  src/main/java/com/beyond/easycheck/roomType/application/service/RoomTypeService.java
  src/main/java/com/beyond/easycheck/roomType/ui/controller/RoomTypeController.java
Labels: Backend, Feat

#40 [feat/#21] feat/#21/update delete theme parks
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkOperationUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/ui/controller/ThemeParkController.java
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkUpdateRequest.java
Labels: Backend, Feat

#42 [feat/#36] feat/#36/ReadRoomType
  src/main/java/com/beyond/easycheck/roomType/application/service/RoomTypeService.java
  src/main/java/com/beyond/easycheck/roomType/ui/controller/RoomTypeController.java
  src/main/java/com/beyond/easycheck/roomType/ui/requestbody/RoomTypeReadRequest.java
Labels: Backend, Feat

#43 [feat/#21] feat/#21/update delete theme parks
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkService.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/persistence/entity/ThemeParkEntity.java
Labels: Backend, Feat

#46 [feat/#30] feat/#30/CreateReservationRoom
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/PaymentStatus.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationStatus.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/repository/ReservationRoomRepository.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/requestbody/ReservationRoomCreateRequest.java
Labels: Backend, Feat

#48 [refactor/#47]: refactor/#47/rename themeParks, roomType
  src/main/java/com/beyond/easycheck/roomtypes/application/service/RoomTypeService.java
  src/main/java/com/beyond/easycheck/roomtypes/infrastructure/entity/RoomTypeEntity.java
  src/main/java/com/beyond/easycheck/roomtypes/infrastructure/repository/RoomTypeRepository.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/controller/RoomTypeController.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomTypeCreateRequest.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomTypeReadRequest.java
  src/main/java/com/beyond/easycheck/themeparks/application/service/ThemeParkOperationUseCase.java
  src/main/java/com/beyond/easycheck/themeparks/application/service/ThemeParkReadUseCase.java
  src/main/java/com/beyond/easycheck/themeparks/application/service/ThemeParkService.java
  src/main/java/com/beyond/easycheck/themeparks/exception/ThemeParkMessageType.java
  src/main/java/com/beyond/easycheck/themeparks/infrastructure/persistence/entity/ThemeParkEntity.java
  src/main/java/com/beyond/easycheck/themeparks/infrastructure/persistence/repository/ThemeParkRepository.java
  src/main/java/com/beyond/easycheck/themeparks/ui/controller/ThemeParkController.java
  src/main/java/com/beyond/easycheck/themeparks/ui/requestbody/ThemeParkCreateRequest.java
  src/main/java/com/beyond/easycheck/themeparks/ui/requestbody/ThemeParkUpdateRequest.java
  src/main/java/com/beyond/easycheck/themeparks/ui/view/ApiResponseView.java
  src/main/java/com/beyond/easycheck/themeparks/ui/view/ThemeParkView.java
Labels: Backend, Refactor

#53 [feat/#44/CRUDAttraction] Attraction CRUD 기능 구현
  src/main/java/com/beyond/easycheck/attractions/application/service/AttractionOperationUseCase.java
  src/main/java/com/beyond/easycheck/attractions/application/service/AttractionReadUseCase.java
  src/main/java/com/beyond/easycheck/attractions/application/service/AttractionService.java
  src/main/java/com/beyond/easycheck/attractions/exception/AttractionMessageType.java
  src/main/java/com/beyond/easycheck/attractions/infrastructure/entity/AttractionEntity.java
  src/main/java/com/beyond/easycheck/attractions/infrastructure/repository/AttractionRepository.java
  src/main/java/com/beyond/easycheck/attractions/ui/controller/AttractionController.java
  src/main/java/com/beyond/easycheck/attractions/ui/requestbody/AttractionRequest.java
  src/main/java/com/beyond/easycheck/attractions/ui/view/AttractionView.java
  src/main/java/com/beyond/easycheck/common/exception/CommonMessageType.java
  src/main/java/com/beyond/easycheck/common/ui/view/ApiResponseView.java
  src/main/java/com/beyond/easycheck/themeparks/ui/controller/ThemeParkController.java
Labels: Backend, Feat

#56 Refactor/#55/refactor
  src/main/java/com/beyond/easycheck/EasycheckApplication.java
  src/main/java/com/beyond/easycheck/accomodations/application/service/AccommodationService.java
  src/main/java/com/beyond/easycheck/accomodations/exception/AccommodationMessageType.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/entity/AccommodationEntity.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/entity/AccommodationType.java
  src/main/java/com/beyond/easycheck/accomodations/infrastructure/repository/AccommodationRepository.java
  src/main/java/com/beyond/easycheck/accomodations/ui/controller/AccommodationController.java
  src/main/java/com/beyond/easycheck/accomodations/ui/requestbody/AccommodationCreateRequest.java
  src/main/java/com/beyond/easycheck/accomodations/ui/requestbody/AccommodationUpdateRequest.java
  src/main/java/com/beyond/easycheck/accomodations/ui/view/AccommodationView.java
  src/main/java/com/beyond/easycheck/additionalservices/application/service/AdditionalServiceService.java
  src/main/java/com/beyond/easycheck/additionalservices/exception/AdditionalServiceMessageType.java
  src/main/java/com/beyond/easycheck/additionalservices/infrastructure/entity/AdditionalServiceEntity.java
  src/main/java/com/beyond/easycheck/additionalservices/infrastructure/repository/AdditionalServiceRepository.java
  src/main/java/com/beyond/easycheck/additionalservices/ui/controller/AdditionalServiceController.java
  src/main/java/com/beyond/easycheck/additionalservices/ui/requestbody/AdditionalServiceCreateRequest.java
  src/main/java/com/beyond/easycheck/additionalservices/ui/requestbody/AdditionalServiceUpdateRequest.java
  src/main/java/com/beyond/easycheck/additionalservices/ui/view/AdditionalServiceView.java
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/PaymentStatus.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationStatus.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/repository/ReservationRoomRepository.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/requestbody/ReservationRoomCreateRequest.java
  src/main/java/com/beyond/easycheck/roomtypes/application/service/RoomTypeService.java
  src/main/java/com/beyond/easycheck/roomtypes/infrastructure/entity/RoomTypeEntity.java
  src/main/java/com/beyond/easycheck/roomtypes/infrastructure/repository/RoomTypeRepository.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/controller/RoomTypeController.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomTypeCreateRequest.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomTypeReadRequest.java
  src/main/java/com/beyond/easycheck/roomtypes/ui/requestbody/RoomTypeUpdateRequest.java
  src/main/java/com/beyond/easycheck/suggestion/application/service/SuggestionService.java
  src/main/java/com/beyond/easycheck/suggestion/infrastructure/persistence/entity/AgreementType.java
  src/main/java/com/beyond/easycheck/suggestion/infrastructure/persistence/entity/SuggestionEntity.java
  src/main/java/com/beyond/easycheck/suggestion/infrastructure/persistence/repository/SuggestionsRepository.java
  src/main/java/com/beyond/easycheck/suggestion/ui/controller/SuggestionController.java
  src/main/java/com/beyond/easycheck/suggestion/ui/requestbody/SuggestionCreateRequest.java
  src/main/java/com/beyond/easycheck/themeparks/application/service/ThemeParkOperationUseCase.java
  src/main/java/com/beyond/easycheck/themeparks/application/service/ThemeParkReadUseCase.java
  src/main/java/com/beyond/easycheck/themeparks/application/service/ThemeParkService.java
  src/main/java/com/beyond/easycheck/themeparks/exception/ThemeParkMessageType.java
  src/main/java/com/beyond/easycheck/themeparks/infrastructure/persistence/entity/ThemeParkEntity.java
  src/main/java/com/beyond/easycheck/themeparks/infrastructure/persistence/repository/ThemeParkRepository.java
  src/main/java/com/beyond/easycheck/themeparks/ui/controller/ThemeParkController.java
  src/main/java/com/beyond/easycheck/themeparks/ui/requestbody/ThemeParkCreateRequest.java
  src/main/java/com/beyond/easycheck/themeparks/ui/requestbody/ThemeParkUpdateRequest.java
  src/main/java/com/beyond/easycheck/themeparks/ui/view/ApiResponseView.java
  src/main/java/com/beyond/easycheck/themeparks/ui/view/ThemeParkView.java
Labels: Backend, Refactor

#23 [feat/#4] feat/#4/CreateRooms
  src/main/java/com/beyond/easycheck/EasycheckApplication.java
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomEntity.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomStatus.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/repository/RoomRepository.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomCreateRequest.java
Labels: Backend, Feat

#32 [feat/#28] feat/#28/ReadSuggestions
  src/main/java/com/beyond/easycheck/suggestions/application/service/SuggestionService.java
  src/main/java/com/beyond/easycheck/suggestions/exception/SuggestionMessageType.java
  src/main/java/com/beyond/easycheck/suggestions/infrastructure/persistence/entity/AgreementType.java
  src/main/java/com/beyond/easycheck/suggestions/infrastructure/persistence/entity/SuggestionEntity.java
  src/main/java/com/beyond/easycheck/suggestions/infrastructure/persistence/repository/SuggestionsRepository.java
  src/main/java/com/beyond/easycheck/suggestions/ui/controller/SuggestionController.java
  src/main/java/com/beyond/easycheck/suggestions/ui/requestbody/SuggestionCreateRequest.java
  src/main/java/com/beyond/easycheck/suggestions/ui/view/SuggestionView.java
Labels: Backend, Feat

#51 [feat/#37/CreateNotices] 공지사항 등록 기능 구현
  src/main/java/com/beyond/easycheck/notices/application/service/NoticesService.java
  src/main/java/com/beyond/easycheck/notices/infrastructure/persistence/entity/NoticesEntity.java
  src/main/java/com/beyond/easycheck/notices/infrastructure/persistence/repository/NoticesRepository.java
  src/main/java/com/beyond/easycheck/notices/ui/controller/NoticesController.java
  src/main/java/com/beyond/easycheck/notices/ui/requestbody/NoticesCreateRequest.java
Labels: Backend, Feat

#59 chore: main -> develop 머지
  src/main/java/com/beyond/easycheck/infrastructure/persistence/entity/AgreementType.java
  src/main/java/com/beyond/easycheck/infrastructure/persistence/repository/SuggestionsRepository.java
  src/main/java/com/beyond/easycheck/suggestion/application/service/SuggestionService.java
  src/main/java/com/beyond/easycheck/suggestion/infrastructure/persistence/entity/AgreementType.java
  src/main/java/com/beyond/easycheck/suggestion/infrastructure/persistence/entity/SuggestionEntity.java
  src/main/java/com/beyond/easycheck/suggestion/infrastructure/persistence/repository/SuggestionsRepository.java
  src/main/java/com/beyond/easycheck/suggestion/ui/controller/SuggestionController.java
  src/main/java/com/beyond/easycheck/suggestion/ui/requestbody/SuggestionCreateRequest.java
Labels: !HOTFIX

#60 README.md 수정
  README.md
Labels: Chore

#67 Fix/#64/package
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/suggestion/exception/SuggestionMessageType.java
  src/main/java/com/beyond/easycheck/suggestions/application/service/SuggestionService.java
  src/main/java/com/beyond/easycheck/suggestions/infrastructure/persistence/entity/AgreementType.java
  src/main/java/com/beyond/easycheck/suggestions/infrastructure/persistence/entity/SuggestionEntity.java
  src/main/java/com/beyond/easycheck/suggestions/infrastructure/persistence/repository/SuggestionsRepository.java
  src/main/java/com/beyond/easycheck/suggestions/ui/controller/SuggestionController.java
  src/main/java/com/beyond/easycheck/suggestions/ui/requestbody/SuggestionCreateRequest.java
  src/main/java/com/beyond/easycheck/suggestions/ui/view/SuggestionView.java
Labels: Fix, !HOTFIX

#71 [Feat/#70/Update Notices] 공지사항 수정 기능 구현
  src/main/java/com/beyond/easycheck/notices/application/service/NoticesService.java
  src/main/java/com/beyond/easycheck/notices/infrastructure/persistence/entity/NoticesEntity.java
  src/main/java/com/beyond/easycheck/notices/ui/controller/NoticesController.java
  src/main/java/com/beyond/easycheck/notices/ui/requestbody/NoticesUpdateRequest.java
Labels: Backend, Feat

#73 [feat/#50] feat/#50/ReadReservation
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/exception/ReservationRoomMessageType.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/view/ReservationRoomView.java
Labels: Backend, Feat

#75 [feat/#74] feat/#74/CancelReservation
  src/main/java/com/beyond/easycheck/reservationroom/application/service/ReservationRoomService.java
  src/main/java/com/beyond/easycheck/reservationroom/infrastructure/entity/ReservationRoomEntity.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/controller/ReservationRoomController.java
  src/main/java/com/beyond/easycheck/reservationroom/ui/requestbody/ReservationRoomUpdateRequest.java
Labels: Backend, Feat

#77 [feat/#76] feat/#76/Facility
  src/main/java/com/beyond/easycheck/facilities/application/service/FacilityService.java
  src/main/java/com/beyond/easycheck/facilities/exception/FacilityMessageType.java
  src/main/java/com/beyond/easycheck/facilities/infrastructure/entity/AvailableStatus.java
  src/main/java/com/beyond/easycheck/facilities/infrastructure/entity/FacilityEntity.java
  src/main/java/com/beyond/easycheck/facilities/infrastructure/repository/FacilityRepository.java
  src/main/java/com/beyond/easycheck/facilities/ui/controller/FacilityController.java
  src/main/java/com/beyond/easycheck/facilities/ui/requestbody/FacilityCreateRequest.java
  src/main/java/com/beyond/easycheck/facilities/ui/requestbody/FacilityUpdateRequest.java
  src/main/java/com/beyond/easycheck/facilities/ui/view/FacilityView.java
Labels: Backend, Feat

#72 [feat/#11] feat/#11/user
  src/main/java/com/beyond/easycheck/mail/application/service/MailService.java
  src/main/java/com/beyond/easycheck/mail/application/service/MailServiceImpl.java
  src/main/java/com/beyond/easycheck/mail/exception/MailMessageType.java
  src/main/java/com/beyond/easycheck/mail/infrastructure/persistence/redis/entity/VerificationCodeEntity.java
  src/main/java/com/beyond/easycheck/mail/infrastructure/persistence/redis/entity/VerifiedEmailEntity.java
  src/main/java/com/beyond/easycheck/mail/infrastructure/persistence/redis/repository/VerificationCodeRepository.java
  src/main/java/com/beyond/easycheck/mail/infrastructure/persistence/redis/repository/VerifiedEmailRepository.java
  src/main/java/com/beyond/easycheck/mail/ui/controller/EmailController.java
  src/main/java/com/beyond/easycheck/mail/ui/requestbody/VerificationCodeRequest.java
  src/main/java/com/beyond/easycheck/mail/ui/requestbody/VerificationTargetEmailRequest.java
  src/main/java/com/beyond/easycheck/user/application/domain/EasyCheckUserDetails.java
  src/main/java/com/beyond/easycheck/user/application/domain/UserRole.java
  src/main/java/com/beyond/easycheck/user/application/service/UserOperationUseCase.java
  src/main/java/com/beyond/easycheck/user/application/service/UserReadUseCase.java
  src/main/java/com/beyond/easycheck/user/application/service/UserService.java
  src/main/java/com/beyond/easycheck/user/exception/UserMessageType.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/permission/PermissionEntity.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/role/RoleEntity.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/role/UserPermissionEntity.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/user/UserEntity.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/repository/RoleJpaRepository.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/repository/UserJpaRepository.java
  src/main/java/com/beyond/easycheck/user/ui/controller/UserController.java
  src/main/java/com/beyond/easycheck/user/ui/requestbody/UserRegisterRequest.java
  src/test/java/com/beyond/easycheck/mail/application/service/MailServiceImplTest.java
  src/test/java/com/beyond/easycheck/user/application/service/UserServiceTest.java
  src/test/java/com/beyond/easycheck/user/ui/controller/UserControllerTest.java
  src/test/resources/sql/user.sql
Labels: Backend, Feat

#69 [feat/#62] feat/#62/CRUDRrooms
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/rooms/infrastructure/entity/RoomEntity.java
  src/main/java/com/beyond/easycheck/rooms/ui/controller/RoomController.java
  src/main/java/com/beyond/easycheck/rooms/ui/requestbody/RoomUpdateRequest.java
  src/main/java/com/beyond/easycheck/rooms/ui/views/RoomView.java
Labels: Backend, Feat

#87 refactor/#70/UpdateNotices
  src/main/java/com/beyond/easycheck/notices/application/service/NoticesService.java
  src/main/java/com/beyond/easycheck/notices/infrastructure/persistence/entity/NoticesEntity.java
  src/main/java/com/beyond/easycheck/notices/ui/controller/NoticesController.java
  src/main/java/com/beyond/easycheck/notices/ui/requestbody/NoticesCreateRequest.java
  src/main/java/com/beyond/easycheck/notices/ui/view/NoticesView.java
Labels: Backend, Refactor

#91 [feat/#86] feat/#86/Payment
  src/main/java/com/beyond/easycheck/payments/application/service/PaymentService.java
  src/main/java/com/beyond/easycheck/payments/exception/PaymentMessageType.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/entity/CompletionStatus.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/entity/PaymentEntity.java
  src/main/java/com/beyond/easycheck/payments/infrastructure/repository/PaymentRepository.java
  src/main/java/com/beyond/easycheck/payments/ui/controller/PaymentController.java
  src/main/java/com/beyond/easycheck/payments/ui/requestbody/PaymentCreateRequest.java
  src/main/java/com/beyond/easycheck/payments/ui/requestbody/PaymentUpdateRequest.java
  src/main/java/com/beyond/easycheck/payments/ui/view/PaymentView.java
Labels: Backend, Feat

#92 [feat/#78] feat/#78/Ticket
  src/main/java/com/beyond/easycheck/attractions/application/service/AttractionService.java
  src/main/java/com/beyond/easycheck/attractions/infrastructure/entity/AttractionEntity.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkOperationUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkReadUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkService.java
  src/main/java/com/beyond/easycheck/themeParks/exception/ThemeParkMessageType.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/entity/ThemeParkEntity.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/repository/ThemeParkRepository.java
  src/main/java/com/beyond/easycheck/themeParks/ui/controller/ThemeParkController.java
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkCreateRequest.java
  src/main/java/com/beyond/easycheck/themeParks/ui/requestbody/ThemeParkUpdateRequest.java
  src/main/java/com/beyond/easycheck/themeParks/ui/view/ThemeParkView.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketOperationUseCase.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketReadUseCase.java
  src/main/java/com/beyond/easycheck/tickets/application/service/TicketService.java
  src/main/java/com/beyond/easycheck/tickets/exception/TicketMessageType.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/entity/TicketEntity.java
  src/main/java/com/beyond/easycheck/tickets/infrastructure/repository/TicketRepository.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketController.java
  src/main/java/com/beyond/easycheck/tickets/ui/requestbody/TicketRequest.java
  src/main/java/com/beyond/easycheck/tickets/ui/view/TicketView.java
Labels: Backend, Feat, Refactor

#93 [refactor/#28] refactor/#28/ReadSuggestions
  src/main/java/com/beyond/easycheck/suggestion/application/service/SuggestionService.java
  src/main/java/com/beyond/easycheck/suggestion/infrastructure/persistence/entity/SuggestionEntity.java
  src/main/java/com/beyond/easycheck/suggestion/ui/controller/SuggestionController.java
  src/main/java/com/beyond/easycheck/suggestion/ui/requestbody/SuggestionCreateRequest.java
  src/main/java/com/beyond/easycheck/suggestion/ui/view/SuggestionView.java
Labels: Backend, Refactor

#94 [refactor/#70] refactor/#70/UpdateNotices
  src/main/java/com/beyond/easycheck/notices/application/service/NoticesService.java
Labels: Backend, Refactor

#90 [refactor/#89] refactor/#89/AddErrorMsg
  src/main/java/com/beyond/easycheck/rooms/application/service/RoomService.java
  src/main/java/com/beyond/easycheck/roomtypes/application/service/RoomTypeService.java
  src/main/java/com/beyond/easycheck/roomtypes/exception/RoomTypeMessageType.java
Labels: Backend, Refactor

#88 [feat/#81] feat/#81/CRUDSeason
  src/main/java/com/beyond/easycheck/seasons/application/service/SeasonService.java
  src/main/java/com/beyond/easycheck/seasons/exception/SeasonMessageType.java
  src/main/java/com/beyond/easycheck/seasons/infrastructure/entity/SeasonEntity.java
  src/main/java/com/beyond/easycheck/seasons/infrastructure/repository/SeasonRepository.java
  src/main/java/com/beyond/easycheck/seasons/ui/controller/SeasonController.java
  src/main/java/com/beyond/easycheck/seasons/ui/requestbody/SeasonCreateRequest.java
  src/main/java/com/beyond/easycheck/seasons/ui/requestbody/SeasonUpdateRequest.java
  src/main/java/com/beyond/easycheck/seasons/ui/view/SeasonView.java
Labels: Backend, Feat

#85 [feat/#80] feat/#80/auth
  build.gradle
  src/main/java/com/beyond/easycheck/common/security/config/EasyCheckSecurityConfig.java
  src/main/java/com/beyond/easycheck/common/security/exception/JwtMessageType.java
  src/main/java/com/beyond/easycheck/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/beyond/easycheck/common/security/provider/JwtAuthenticationProvider.java
  src/main/java/com/beyond/easycheck/common/security/utils/JwtUtil.java
  src/main/java/com/beyond/easycheck/user/application/domain/EasyCheckUserDetails.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/permission/PermissionEntity.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/entity/user/UserEntity.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/repository/UserJpaRepository.java
  src/test/resources/sql/user.sql
Labels: Feat

#96 [feat/#80] feat/#80/auth
  src/main/java/com/beyond/easycheck/common/security/config/EasyCheckSecurityConfig.java
  src/main/java/com/beyond/easycheck/common/security/infrastructure/persistence/entity/ExpiredAccessToken.java
  src/main/java/com/beyond/easycheck/common/security/infrastructure/persistence/repository/ExpiredAccessTokenJpaRepository.java
  src/main/java/com/beyond/easycheck/common/security/provider/JwtAuthenticationProvider.java
  src/main/java/com/beyond/easycheck/common/security/utils/JwtUtil.java
  src/main/java/com/beyond/easycheck/user/application/service/UserOperationUseCase.java
  src/main/java/com/beyond/easycheck/user/application/service/UserReadUseCase.java
  src/main/java/com/beyond/easycheck/user/application/service/UserService.java
  src/main/java/com/beyond/easycheck/user/exception/UserMessageType.java
  src/main/java/com/beyond/easycheck/user/infrastructure/persistence/mariadb/repository/UserJpaRepository.java
  src/main/java/com/beyond/easycheck/user/ui/controller/UserController.java
  src/main/java/com/beyond/easycheck/user/ui/requestbody/ChangePasswordRequest.java
  src/main/java/com/beyond/easycheck/user/ui/requestbody/UserLoginRequest.java
  src/main/java/com/beyond/easycheck/user/ui/view/UserLoginView.java
  src/test/java/com/beyond/easycheck/user/application/service/UserServiceTest.java
  src/test/java/com/beyond/easycheck/user/ui/controller/UserControllerTest.java
Labels: Feat

#102 [hotfix/#100/jwt] hotfix/#100/jwt userId 파싱 반환값 수정
  src/main/java/com/beyond/easycheck/common/security/utils/JwtUtil.java
Labels: !HOTFIX

#97 [feat/#95] feat/#95/ThemeparkCorrelation
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkOperationUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkReadUseCase.java
  src/main/java/com/beyond/easycheck/themeParks/application/service/ThemeParkService.java
  src/main/java/com/beyond/easycheck/themeParks/exception/ThemeParkMessageType.java
  src/main/java/com/beyond/easycheck/themeParks/infrastructure/entity/ThemeParkEntity.java
  src/main/java/com/beyond/easycheck/themeParks/ui/controller/ThemeParkController.java
Labels: Backend, Feat

#103 [refactor/#98] refactor/#98/addSwaggerAnnotation
  src/main/java/com/beyond/easycheck/attractions/ui/controller/AttractionController.java
  src/main/java/com/beyond/easycheck/themeParks/ui/controller/ThemeParkController.java
  src/main/java/com/beyond/easycheck/tickets/ui/controller/TicketController.java
Labels: Backend, Refactor

#106 [feat/#99] feat/#99/CRUDRoomrate
  src/main/java/com/beyond/easycheck/roomrates/application/service/RoomrateService.java
  src/main/java/com/beyond/easycheck/roomrates/exception/RoomrateMessageType.java
  src/main/java/com/beyond/easycheck/roomrates/infrastructure/entity/RoomrateEntity.java
  src/main/java/com/beyond/easycheck/roomrates/infrastructure/entity/RoomrateType.java
  src/main/java/com/beyond/easycheck/roomrates/infrastructure/repository/RoomrateRepository.java
  src/main/java/com/beyond/easycheck/roomrates/ui/controller/RoomrateController.java
  src/main/java/com/beyond/easycheck/roomrates/ui/requestbody/RoomrateCreateRequest.java
  src/main/java/com/beyond/easycheck/roomrates/ui/requestbody/RoomrateUpdateRequest.java
  src/main/java/com/beyond/easycheck/roomrates/ui/view/RoomrateView.java
Labels: Backend, Feat

#107 [feat/#101] feat/#101/ReservastionService
  src/main/java/com/beyond/easycheck/reservationservices/application/service/ReservationServiceService.java
  src/main/java/com/beyond/easycheck/reservationservices/exception/ReservationServiceMessageType.java
  src/main/java/com/beyond/easycheck/reservationservices/infrastructure/entity/ReservationServiceEntity.java
  src/main/java/com/beyond/easycheck/reservationservices/infrastructure/entity/ReservationServiceStatus.java
  src/main/java/com/beyond/easycheck/reservationservices/infrastructure/repository/ReservationServiceRepository.java
  src/main/java/com/beyond/easycheck/reservationservices/ui/controller/ReservationServiceController.java
  src/main/java/com/beyond/easycheck/reservationservices/ui/requestbody/ReservationServiceCreateRequest.java
  src/main/java/com/beyond/easycheck/reservationservices/ui/requestbody/ReservationServiceUpdateRequest.java
  src/main/java/com/beyond/easycheck/reservationservices/ui/view/ReservationServiceView.java
Labels: Backend, Feat
